version: "3"
services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - app-node-modules:/app/node_modules
    environment:
      - AMQP_APP_ID=sandbox
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - INCOMING_QUEUE=attach-to-tangle
      - COMPLETED_QUEUE=attach-complete
      - UPDATE_QUEUE=attach-progress
      - MONGO_CONN=mongodb://mongodb:27017/sandbox
      - IRI_HOST=https://nodes.devnet.iota.org
      - IRI_PORT=443
      - MWM_LIMIT=9
      - NODE_ENV=development
      - SESSION_SECRET=PutTheRandomSecreteHere
    depends_on:
      - rabbitmq
      - mongodb

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker-debian
    volumes:
      - .:/app
      - worker-node-modules:/app/node_modules
    environment:
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - INCOMING_QUEUE=attach-to-tangle
      - COMPLETED_QUEUE=attach-complete
      - UPDATE_QUEUE=attach-progress
      - CCURL_PATH=/opt
    depends_on:
      - api

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672

  mongodb:
    image: mongo
    ports:
      - 27017:27017

volumes:
  app-node-modules:
  worker-node-modules:
